version: 2.1

orbs:
  slack: circleci/slack@4.3.3

slack_success_notify: &slack_success_notify
  slack/notify:
    event: pass
    branch_pattern: master,release
    tag_pattern: v.*
    template: SLACK_TEMPLATE_SUCCESS

slack_fail_notify: &slack_fail_notify
  slack/notify:
    event: fail
    branch_pattern: master,release
    tag_pattern: v.*
    mentions: '@here'
    template: SLACK_TEMPLATE_FAIL

node_image: &node_image cimg/node:18.16.1

executors:
  build:
    docker:
      - image: *node_image
      - image: mongo:4.4
    working_directory: ~/mongo-migrate

commands:
  setup_node_modules:
    description: "Restore Install node_modules"
    steps:
      - restore_cache:
          keys:
            - v1-mongo-migrate-{{ checksum "package.json" }}
      - run:
          name: NPM install
          command: npm install --quiet

      - save_cache:
          key: v1-mongo-migrate-{{ checksum "package.json" }}
          paths:
            - ~/mongo-migrate/node_modules
  push_sbom_to_sca:
    steps:
      - run:
          name: Push SBOM to SCA tool
          command: |
            npm run sbom -- --no-install-deps --project-name mongo-migrate --project-version << pipeline.git.tag >> --server-url https://dt-apiserver.thimble.com --api-key $DT_API_KEY -o bom.json
      - store_artifacts:
          path: bom.json

jobs:
  build:
    executor: build
    steps:
      - checkout

      - setup_node_modules

      - run:
          name: Run tests
          command: npm test

      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package-lock.json

  npm-publish:
    circleci_ip_ranges: true
    docker:
      - image: *node_image
    working_directory: ~/mongo-migrate
    steps:
      - checkout

      - attach_workspace:
          at: ~/mongo-migrate

      - run:
          name: release check
          command: |
            node scripts/release-check.js

      - push_sbom_to_sca

      - run:
          name: npm publish
          command: |
            echo "npm version -> `npm --version`"
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
            npm publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context:
            - slack_context
          filters:
            tags:
              only: /^v.*/
          post-steps:
            - *slack_fail_notify
      - hold:
          type: approval
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - npm-publish:
          context:
            - public_context
            - slack_context
            - deploy_context
          requires:
            - build
            - hold
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
          post-steps:
            - *slack_success_notify
            - *slack_fail_notify
